services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/yourpassword